<div class="page-header"></div>


<div class="row">
    <div class="col-md-6">
        <h4><i class="glyphicon glyphicon-list-alt"></i> Resumo das contas/caixas</h4>
        <hr/>

        <table class="table table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th>Conta</th>
                    <th style="text-align: right; width: 20%;">Saldo</th>
                </tr>
            </thead>
            <tbody>
                <?php $soma = 0; ?>
                <?php foreach ($this->contas as $conta) : ?>
                    <tr>
                        <td class="small"><?php echo $conta->nome; ?></td>
                        <td style="text-align: right; width: 20%;" class="small">
                            <span class="<?php echo($conta->getSaldoAtual() < 0 ? 'fonte_vermelho' : 'fonte_verde'); ?>">
                                <?php echo Zend_Registry::get('currency')->toCurrency($conta->getSaldoAtual()); ?>
                            </span>
                        </td>
                    </tr>
                    <?php $soma = $soma + $conta->getSaldoAtual(); ?>
                <?php endforeach; ?>
            </tbody>
        </table>

        <div class="admin_estatisticas_contas_caixa_linha admin_estatisticas_contas_caixa_linha_total">
            <span class="<?php echo ($soma < 0 ? 'fonte_vermelho' : 'fonte_verde'); ?>">
                <?php echo Zend_Registry::get('currency')->toCurrency($soma); ?>
            </span>
        </div>
    </div>

    <div class="col-md-6">
        <div class="calendar" id="calendar"></div>
    </div>
</div>