<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Título</th>
            <th class="acoes">Vencimento</th>
            <th class="valores">Valor</th>
            <th class="acoes">Situação</th>
            <th class="acoes">Ações</th>
        </tr>
    </thead>
    <tbody>

        <?php foreach ($this->lancamentos as $lancamento) : ?>
            <tr>
                <td>
                    <span class="label <?php echo $lancamento->getLabel(); ?>">
                        <i class="glyphicon glyphicon-tag"></i> <?php echo $lancamento->getCategoria()->nome; ?>
                    </span> &nbsp;
                    <span class="small"><?php echo $lancamento->titulo; ?></span>
                </td>

                <td class="acoes"><span class="small"><?php echo date("d/m/Y", strtotime($lancamento->vencimento)); ?></span></td>
                <td class="valores"><span class="small <?php echo $lancamento->getValorLabel(); ?>"><?php echo $lancamento->getValor(); ?></span></td>
                <td class="acoes"><span class="label <?php echo $lancamento->getLabelSituacao(); ?>"><small><?php echo $lancamento->getSituacao(); ?></small></span></td>
                <td class="acoes">
                    <a href="#" class="btn btn-default btn-xs">Estornar</a>
                </td>

            </tr>

        <?php endforeach; ?>
    </tbody>
</table>

<hr/>

<div class="admin_estatisticas_contas_caixa">
    <div class="admin_estatisticas_contas_caixa_linha">
        <span class="admin_estatisticas_contas_caixa_linha_titulo">Saldo Anterior</span>
        <span class="admin_estatisticas_contas_caixa_linha_valor" style="font-size:10px;;">
            <span class="<?php echo ($this->saldoAnterior < 0 ? 'fonte_vermelho' : 'fonte_verde'); ?>">
                <?php echo Zend_Registry::get('currency')->toCurrency($this->saldoAnterior); ?>
            </span> 
        </span>
    </div>

    <div class="admin_estatisticas_contas_caixa_linha">
        <span class="admin_estatisticas_contas_caixa_linha_titulo">Entradas do período</span>
        <span class="admin_estatisticas_contas_caixa_linha_valor fonte_verde" title="2 receitas cadastradas">+ <?php echo Zend_Registry::get('currency')->toCurrency($this->totalReceitas); ?></span>
        <span class="admin_estatisticas_contas_caixa_linha_de">previsto + <?php echo Zend_Registry::get('currency')->toCurrency($this->previsaoReceitas); ?></span>
    </div>

    <div class="admin_estatisticas_contas_caixa_linha">
        <span class="admin_estatisticas_contas_caixa_linha_titulo">Saídas do período</span>
        <span class="admin_estatisticas_contas_caixa_linha_valor fonte_vermelho" title="0 despesas cadastradas">- <?php echo Zend_Registry::get('currency')->toCurrency($this->totalDespesas); ?></span>
        <span class="admin_estatisticas_contas_caixa_linha_de">previsto - <?php echo Zend_Registry::get('currency')->toCurrency($this->previsaoDespesas); ?></span>
    </div>

    <div class="admin_estatisticas_contas_caixa_linha admin_estatisticas_contas_caixa_linha_total">
        <span class="<?php echo ($this->saldoBalanco < 0 ? 'fonte_vermelho' : 'fonte_verde'); ?>">
            <?php echo Zend_Registry::get('currency')->toCurrency($this->saldoBalanco); ?>
        </span>
    </div>

    <div class="admin_estatisticas_contas_caixa_linha admin_estatisticas_contas_caixa_linha_total_texto">
        previsto <span class="<?php echo ($this->saldoBalancoPrevisto < 0 ? 'fonte_vermelho' : 'fonte_verde'); ?>">
            <?php echo Zend_Registry::get('currency')->toCurrency($this->saldoBalancoPrevisto); ?>
        </span>
    </div>
</div>
