<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Título</th>
            <th class="acoes">Vencimento</th>
            <th class="valores">Valor</th>
            <th class="acoes">Situação</th>
            <th class="acoes">Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->lancamentos as $lancamento) : ?>

            <?php if ($lancamento->tipo == 'T') : ?>

                <tr>
                    <td><span class="small"><?php echo $lancamento->titulo; ?></span></td>
                    <td></td>
                    <td class="valores"><span class="small fonte_azul"><?php echo $lancamento->getValor(); ?></span></td>
                    <td class="acoes"><span class="label label-default small">Transferido em <?php echo date("d/m/Y", strtotime($lancamento->vencimento)); ?></span></td>
                    <td class="acoes">
                        <a href="javascript:void(0)" class="btn btn-danger btn-xs excluir" data-value="<?php echo $lancamento->id; ?>">Excluir</a>
                    </td>
                </tr>

            <?php else : ?>

                <tr>
                    <td>
                        <span class="label <?php echo $lancamento->getLabel(); ?>">
                            <i class="glyphicon glyphicon-tag"></i> <?php echo $lancamento->getCategoria()->nome; ?>
                        </span> &nbsp;
                        <span class="small">
                            <?php echo $lancamento->titulo; ?>
                            <?php echo ($lancamento->parcelas > 1 ? "<span class='label label-default'> ( $lancamento->numeroParcela de $lancamento->parcelas )</span> " : ''); ?>
                        </span>
                    </td>

                    <td class="acoes"><span class="small"><?php echo date("d/m/Y", strtotime($lancamento->vencimento)); ?></span></td>
                    <td class="valores"><span class="small <?php echo $lancamento->getValorLabel(); ?>"><?php echo $lancamento->getValor(); ?></span></td>
                    <td class="acoes"><span class="label <?php echo $lancamento->getLabelSituacao(); ?>"><small><?php echo $lancamento->getSituacao(); ?></small></span></td>
                    <td class="acoes">

                        <?php if ($lancamento->situacao == 0) : ?>
                            <a href="javascript:void(0)" class="btn btn-default btn-xs pagar" data-value="<?php echo $lancamento->id; ?>">Pagar</a>
                            <a href="javascript:void(0)" class="btn btn-danger btn-xs excluir" data-value="<?php echo $lancamento->id; ?>">Excluir</a>
                        <?php endif; ?>

                        <?php if ($lancamento->situacao == 1) : ?>  
                            <a href="javascript:void(0)" class="btn btn-default btn-xs estornar" data-value="<?php echo $lancamento->id; ?>">Estornar</a>
                        <?php endif; ?>
                    </td>

                </tr>
            <?php endif; ?>

        <?php endforeach; ?>
    </tbody>
</table>

<hr/>

<div class="admin_estatisticas_contas_caixa">
    <div class="admin_estatisticas_contas_caixa_linha">
        <span class="admin_estatisticas_contas_caixa_linha_titulo">Saldo Anterior</span>
        <span class="admin_estatisticas_contas_caixa_linha_valor" style="font-size:10px;;">
            <span class="<?php echo ($this->saldoAnterior < 0 ? 'fonte_vermelho' : 'fonte_verde'); ?>">
                <?php echo Zend_Registry::get('currency')->toCurrency($this->saldoAnterior); ?>
            </span> 
        </span>
    </div>

    <div class="admin_estatisticas_contas_caixa_linha">
        <span class="admin_estatisticas_contas_caixa_linha_titulo">Entradas do período</span>
        <span class="admin_estatisticas_contas_caixa_linha_valor fonte_verde" title="2 receitas cadastradas">+ <?php echo Zend_Registry::get('currency')->toCurrency($this->totalReceitas); ?></span>
        <span class="admin_estatisticas_contas_caixa_linha_de">previsto + <?php echo Zend_Registry::get('currency')->toCurrency($this->previsaoReceitas); ?></span>
    </div>

    <div class="admin_estatisticas_contas_caixa_linha">
        <span class="admin_estatisticas_contas_caixa_linha_titulo">Saídas do período</span>
        <span class="admin_estatisticas_contas_caixa_linha_valor fonte_vermelho" title="0 despesas cadastradas">- <?php echo Zend_Registry::get('currency')->toCurrency($this->totalDespesas); ?></span>
        <span class="admin_estatisticas_contas_caixa_linha_de">previsto - <?php echo Zend_Registry::get('currency')->toCurrency($this->previsaoDespesas); ?></span>
    </div>

    <div class="admin_estatisticas_contas_caixa_linha admin_estatisticas_contas_caixa_linha_total">
        <span class="<?php echo ($this->saldoBalanco < 0 ? 'fonte_vermelho' : 'fonte_verde'); ?>">
            <?php echo Zend_Registry::get('currency')->toCurrency($this->saldoBalanco); ?>
        </span>
    </div>

    <div class="admin_estatisticas_contas_caixa_linha admin_estatisticas_contas_caixa_linha_total_texto">
        previsto <span class="<?php echo ($this->saldoBalancoPrevisto < 0 ? 'fonte_vermelho' : 'fonte_verde'); ?>">
            <?php echo Zend_Registry::get('currency')->toCurrency($this->saldoBalancoPrevisto); ?>
        </span>
    </div>
</div>

<script>
    $('.pagar').click(function(e) {
        e.preventDefault();
        var answer = confirm("Confirma o pagamento deste lançamento?");
        if (answer) {

            var id = $(this).attr('data-value');

            $.get("/lancamentos/pagar/id/" + id, function() {
                $('#lancamentos').html('');
                $('#carregando').show();
                $("#lancamentos").load("/lancamentos/carrega");
                $("#carregando").hide();
            });


        } else {
            return false;
        }
    });

    $('.estornar').click(function(e) {
        e.preventDefault();
        var answer = confirm("Confirma o estorno deste lançamento?");
        if (answer) {

            var id = $(this).attr('data-value');

            $.get("/lancamentos/estornar/id/" + id, function() {
                $('#lancamentos').html('');
                $('#carregando').show();
                $("#lancamentos").load("/lancamentos/carrega");
                $("#carregando").hide();
            });


        } else {
            return false;
        }
    });

    $('.excluir').click(function(e) {
        e.preventDefault();
        var answer = confirm("Confirma a exclusão deste lançamento?");
        if (answer) {

            var id = $(this).attr('data-value');

            $.get("/lancamentos/excluir/id/" + id, function() {
                $('#lancamentos').html('');
                $('#carregando').show();
                $("#lancamentos").load("/lancamentos/carrega");
                $("#carregando").hide();
            });


        } else {
            return false;
        }
    });
</script>
