<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Título</th>
            <th class="valores">Valor</th>
            <th class="acoes">Situação</th>
            <th class="acoes">Ações</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><span class="label label-success"><i class="glyphicon glyphicon-tag"></i> Salários</span> <span class="small">Recebimento de salário - Emerson</span></td>
            <td class="valores"><span class="small valorReceita">R$ 1.200,00</span></td>
            <td class="acoes"><span class="label label-success"><small>Pago em 14/11/2014</small></span></td>
            <td class="acoes">
                <a href="#" class="btn btn-default btn-xs">Estornar</a>
            </td>

        </tr>

        <tr>
            <td><span class="label label-danger"><i class="glyphicon glyphicon-tag"></i> Aluguel</span> <span class="small">Aluguel mes 11/2014</span></td>
            <td class="valores"><span class="small valorDespesa">R$ 600,00</span></td>
            <td class="acoes"><span class="label label-danger"><small>Não Pago</small></span></td>
            <td class="acoes">
                <a href="#" class="btn btn-success btn-xs">Pagar</a>
                <a href="#" class="btn btn-danger btn-xs">Excluir</a>
            </td>
        </tr>

        <tr>
            <td><span class="label label-danger"><i class="glyphicon glyphicon-tag"></i> Aluguel</span> <span class="small">Aluguel mes 11/2014</span></td>
            <td class="valores"><span class="small valorDespesa">R$ 600,00</span></td>
            <td class="acoes"><span class="label label-danger"><small>Não Pago</small></span></td>
            <td class="acoes">
                <a href="#" class="btn btn-success btn-xs">Pagar</a>
                <a href="#" class="btn btn-danger btn-xs">Excluir</a>
            </td>
        </tr>

        <tr>
            <td><span class="label label-danger"><i class="glyphicon glyphicon-tag"></i> Aluguel</span> <span class="small">Aluguel mes 11/2014</span></td>
            <td class="valores"><span class="small valorDespesa">R$ 600,00</span></td>
            <td class="acoes"><span class="label label-danger"><small>Não Pago</small></span></td>
            <td class="acoes">
                <a href="#" class="btn btn-success btn-xs">Pagar</a>
                <a href="#" class="btn btn-danger btn-xs">Excluir</a>
            </td>
        </tr>

        <tr>
            <td><span class="label label-success"><i class="glyphicon glyphicon-tag"></i> Salários</span> <span class="small">Recebimento de salário - Emerson</span></td>
            <td class="valores"><span class="small valorReceita">R$ 1.200,00</span></td>
            <td class="acoes"><span class="label label-success"><small>Pago em 14/11/2014</small></span></td>
            <td class="acoes">
                <a href="#" class="btn btn-default btn-xs">Estornar</a>
            </td>
        </tr>
    </tbody>
</table>

<hr/>

<div class="admin_estatisticas_contas_caixa">
    <div class="admin_estatisticas_contas_caixa_linha">
        <span class="admin_estatisticas_contas_caixa_linha_titulo">Saldo Anterior</span>
        <span class="admin_estatisticas_contas_caixa_linha_valor" style="font-size:10px;;">
            <span class="fonte_verde">+ R$ 0,00</span> 
        </span>
    </div>

    <div class="admin_estatisticas_contas_caixa_linha">
        <span class="admin_estatisticas_contas_caixa_linha_titulo">Entradas do período</span>
        <span class="admin_estatisticas_contas_caixa_linha_valor fonte_verde" title="2 receitas cadastradas">+ R$ 1.500,00</span>
        <span class="admin_estatisticas_contas_caixa_linha_de">previsto + R$ 1.500,00</span>
    </div>

    <div class="admin_estatisticas_contas_caixa_linha">
        <span class="admin_estatisticas_contas_caixa_linha_titulo">Saídas do período</span>
        <span class="admin_estatisticas_contas_caixa_linha_valor fonte_vermelho" title="0 despesas cadastradas">- R$ 0,00</span>
        <span class="admin_estatisticas_contas_caixa_linha_de">previsto - R$ 0,00</span>
    </div>

    <div class="admin_estatisticas_contas_caixa_linha admin_estatisticas_contas_caixa_linha_total">
        <span class="fonte_verde">+ R$ 1.500,00</span>
    </div>

    <div class="admin_estatisticas_contas_caixa_linha admin_estatisticas_contas_caixa_linha_total_texto">
        previsto <span class="fonte_verde">+ R$ 1.500,00</span>
    </div>
</div>
