<div class="row">
    <div class="col-md-12">
        <h2>Lançamentos</h2>
        <hr/>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <a href="/contas/add" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-arrow-up"></i> Incluir Receita</a>
        <a href="/contas/add" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-arrow-down"></i> Incluir Despesa</a>
        <a href="/contas/add" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-resize-vertical"></i> Transferência entre contas</a>

        <div class="btn-group pull-right btn-group-sm">
            <a href="#" class="btn btn-default" title="Mês Anterior" data-toggle="tooltip" data-placement="bottom"><i class="glyphicon glyphicon-arrow-left"></i></a>
            <a href="#" class="btn btn-default" style="width: 518px;"><span style="font-weight: bold;">Novembro de 2014</span></a>
            <a href="#" class="btn btn-default" title="Próximo Mês" data-toggle="tooltip" data-placement="bottom"><i class="glyphicon glyphicon-arrow-right"></i></a>
        </div>
    </div>
</div>

<br/>

<div class="row">
    <div class="col-md-12">
        <div id="filtros" class="pull-right">
            <div class="btn-group btn-group-xs">
                <a href="javascript:void(0);" class="btn btn-default" data-value="" id="filtro-tipo">Receitas e Despesas</a>
                <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="javascript:void(0);" data-value="R" class="filtro-tipo">Somente Receitas</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);" data-value="D" class="filtro-tipo">Somente Despesas</a>
                    </li>
                </ul>
            </div>

            <div class="btn-group btn-group-xs">
                <a href="#" class="btn btn-default" id="filtro-categoria" data-value="">Todas as Categorias</a>
                <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="javascript:void(0);" data-value="1" class="filtro-categoria">Moradia</a></li>
                    <li><a href="javascript:void(0);" data-value="2" class="filtro-categoria">Alimentação</a></li>
                    <li><a href="javascript:void(0);" data-value="3" class="filtro-categoria">Transporte</a></li>
                </ul>
            </div>

            <div class="btn-group btn-group-xs">
                <a href="javascript:void(0);" class="btn btn-default" data-value="" id="filtro-situacao">Todas as Situações</a>
                <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="javascript:void(0);" data-value="0" class="filtro-situacao">Contas Pagas/Recebidas</a></li>
                    <li><a href="javascript:void(0);" data-value="1" class="filtro-situacao">Contas não Pagas/Recebidas</a></li>
                </ul>
            </div>

            <div class="btn-group btn-group-xs">
                <a href="javascript:void(0);" class="btn btn-default" data-value="" id="filtro-caixa">Todas as Contas</a>
                <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="javascript:void(0);" data-value="0" class="filtro-caixa">Caixa</a></li>
                    <li><a href="javascript:void(0);" data-value="1" class="filtro-caixa">Banco Itaú</a></li>
                    <li><a href="javascript:void(0);" data-value="2" class="filtro-caixa">Banco Hsbc</a></li>
                    <li><a href="javascript:void(0);" data-value="3" class="filtro-caixa">Banco Caixa</a></li>
                </ul>
            </div>
        </div>

    </div>
</div>

<br/>

<div style="text-align: center; margin-top: 30px; display: none;" id="carregando">
    <span><img src="/img/loader_sessoes.gif" alt=""></span>
</div>

<div class="row">
    <div class="col-md-12" id="lancamentos"></div>
</div>

<script>
    $(document).ready(function() {
        $('#carregando').show();
        $("#lancamentos").load("/lancamentos/carrega", function() {
            $('#carregando').hide();
        });
    });

    lancamentosUI = {
        filtrar: function() {
            var tipo = $("#filtro-tipo").attr('data-value');
            var categoria = $("#filtro-categoria").attr('data-value');
            var situacao = $("#filtro-situacao").attr('data-value');
            var caixa = $("#filtro-caixa").attr('data-value');

            console.log('tipo: ' + tipo + ' categoria: ' + categoria + ' situacao: ' + situacao + ' caixa: ' + caixa);

            $('#lancamentos').html('');

            $('#carregando').show();

            $.post("/lancamentos/carrega", {tipo: tipo, categoria: categoria, situacao: situacao, caixa: caixa}, function(data) {
                $("#lancamentos").html(data);
                $("#carregando").hide();
            });
        },
        trocaInformacoes: function(id, classe) {
            var text = id.text();
            var valor = id.attr('data-value');

            id.text(classe.text());
            classe.text(text);

            id.attr('data-value', classe.attr('data-value'));
            classe.attr('data-value', valor);
        }
    };

    $('.filtro-tipo').click(function() {
        lancamentosUI.trocaInformacoes($('#filtro-tipo'), $(this));
        lancamentosUI.filtrar();
    });

    $('.filtro-categoria').click(function() {
        lancamentosUI.trocaInformacoes($('#filtro-categoria'), $(this));
        lancamentosUI.filtrar();
    });

    $('.filtro-situacao').click(function() {
        lancamentosUI.trocaInformacoes($('#filtro-situacao'), $(this));
        lancamentosUI.filtrar();
    });

    $('.filtro-caixa').click(function() {
        lancamentosUI.trocaInformacoes($('#filtro-caixa'), $(this));
        lancamentosUI.filtrar();
    });


</script>