<div class="row">
    <div class="col-md-12">
        <h2>Nova Conta/Caixa</h2>
        <hr/>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" role="form" action="" method="post">
            <div class="form-group">
                <label for="nome" class="col-sm-2 control-label">Nome</label>
                <div class="col-sm-10">
                    <input type="text" name="nome" class="form-control" id="nome" required="true">
                </div>
            </div>


            <div class="form-group">
                <label for="descricao" class="col-sm-2 control-label">Descrição</label>
                <div class="col-sm-10">
                    <textarea name="descricao" id="descricao" class="form-control" rows="3"></textarea>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Salvar Dados</button>
                    <a href="/contas" class="btn btn-default">Cancelar</a>
                </div>
            </div>
        </form>
    </div>
</div>